// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SuperMarket.Models;

[PrimaryKey("FavoriteID", "UserID")]
[Table("AddFavorite")]
public partial class AddFavorite
{
    [Key]
    public int FavoriteID { get; set; }

    [Key]
    public int UserID { get; set; }

    public int? ProductID { get; set; }

    [ForeignKey("FavoriteID")]
    [InverseProperty("AddFavorites")]
    public virtual Favorite Favorite { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("AddFavorites")]
    public virtual Product Product { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("AddFavorites")]
    public virtual User User { get; set; }
}