// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SuperMarket.Models;

public partial class Favorite
{
    [Key]
    public int ID { get; set; }

    public DateOnly? Created_At { get; set; }

    [InverseProperty("Favorite")]
    public virtual ICollection<AddFavorite> AddFavorites { get; set; } = new List<AddFavorite>();
}