// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SuperMarket.Models;

[Table("Order")]
public partial class Order
{
    [Key]
    public int ID { get; set; }

    public DateOnly? Date { get; set; }

    public double? TotalPrice { get; set; }

    [StringLength(50)]
    public string Payment_Method { get; set; }

    [StringLength(50)]
    public string Customer_Name { get; set; }

    [StringLength(50)]
    public string Customer_Phone { get; set; }

    public int? UserID { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<ProductOrder> ProductOrders { get; set; } = new List<ProductOrder>();

    [ForeignKey("UserID")]
    [InverseProperty("Orders")]
    public virtual User User { get; set; }
}