// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SuperMarket.Models;

[PrimaryKey("OrderID", "ProductID")]
[Table("ProductOrder")]
public partial class ProductOrder
{
    [Key]
    public int OrderID { get; set; }

    [Key]
    public int ProductID { get; set; }

    public int? Quantity { get; set; }

    [ForeignKey("OrderID")]
    [InverseProperty("ProductOrders")]
    public virtual Order Order { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("ProductOrders")]
    public virtual Product Product { get; set; }
}