// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SuperMarket.Models;

[Table("Product")]
public partial class Product
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    public int? Price { get; set; }

    public string Image { get; set; }

    public int? NumOfStock { get; set; }

    public int? CategoryID { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<AddFavorite> AddFavorites { get; set; } = new List<AddFavorite>();

    [ForeignKey("CategoryID")]
    [InverseProperty("Products")]
    public virtual Category Category { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<ProductOrder> ProductOrders { get; set; } = new List<ProductOrder>();

    [InverseProperty("Product")]
    public virtual ICollection<Supply> Supplies { get; set; } = new List<Supply>();
}