// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SuperMarket.Models;

[PrimaryKey("ProductID", "SupplierID")]
[Table("Supply")]
public partial class Supply
{
    [Key]
    public int ProductID { get; set; }

    [Key]
    public int SupplierID { get; set; }

    public int? UnitofPrize { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("Supplies")]
    public virtual Product Product { get; set; }

    [ForeignKey("SupplierID")]
    [InverseProperty("Supplies")]
    public virtual Supplier Supplier { get; set; }
}