// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SuperMarket.Models;

[Table("User")]
public partial class User
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    public string Password { get; set; }

    [StringLength(50)]
    public string Fname { get; set; }

    [StringLength(50)]
    public string LName { get; set; }

    [StringLength(50)]
    public string Email { get; set; }

    [StringLength(50)]
    public string Role { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<AddFavorite> AddFavorites { get; set; } = new List<AddFavorite>();

    [InverseProperty("User")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}